add-bookings
iwfua/java-shareit pull request #2
Opened 2024-10-23 12:10 UTC by iwfua

2024-10-24 12:15 UTC, YazykovMikhail requested changes

2024-10-24 12:15 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
>      public ItemDto addItem(@Valid @RequestBody ItemDto itemDTO,
Используй разные dto для запроса и ответа. Потому что там на входе и на выходе разные данные.
Для создания идема не нужна эта куча поле, тогда зачем они там? нужно только то что реально используется. 
Можно разделять дто на 
```
ItemRequest
ItemResponse 
```
Но стоит обратить внимание, что и запросы/ответы от метода к методу могут отличаться, например запрос на добаление и обноления имеет яно разные поля, при добавлении не нужно id 
Поэтому чаще всего разделяют на конкретные дто для конкретных методов, например:
```
CreateItemRequest
CreateItemResponse
```
```
UpdateItemRequest
UpdateItemResponse
```
Если ответы всех эндпоинтов одинаковые, допускается испоьзования одного дто для ответов, например:
ItemResponse
Но например при создании итем точно в ответе не нужны поля
    ```
private BookingRequestDto lastBooking;

    private BookingRequestDto nextBooking;

    private List<CommentDto> comments;
```
Ведь ничего этого не убдет, пожтому стоит сделать отдельное дто

2024-10-24 12:15 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
>      public ItemDto addItem(@Valid @RequestBody ItemDto itemDTO,
И так во всех контроллерах, иначе потом будет не понятно, зачем в тех или иных метоха те или иные поля, почему они пустые или что с ними делать и что убдет если их передать.

2024-10-24 12:15 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        // Получаем все вещи пользователя
Вот тут как раз будет вызывать Бронирования
```
		List<Booking> approvedBookings;
		if (item.getOwner().getId() == userId) {
			approvedBookings = bookingRepository.findApprovedForItems(List.of(item), Sort.by(DESC, "start"));
		} else {
			approvedBookings = Collections.emptyList();
		}
```

и потом передавать этот список в икомментарии вот в татод что бы определить последнее и следюущее бронировани и сделать дто:

```
private ItemInfoResponse toItemInfoResponse(Item item, List<Booking> bookings, List<Comment> comments) {
		LocalDateTime now = LocalDateTime.now();
		Booking lastBooking = bookings.stream()
				.filter(b -> b.isLastOrCurrent(now))
				.findFirst()
				.orElse(null);

		Booking nextBooking = bookings.stream()
				.filter(b -> b.isFuture(now))
				.reduce((first, second) -> second)
				.orElse(null);

		return ItemMapper.toItemInfoResponse(item, comments, lastBooking, nextBooking);
	}
```

2024-10-26 09:57 UTC, iwfua commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long ownerId;
исправил

2024-10-26 09:57 UTC, iwfua commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      @NotBlank
исправил

2024-10-26 09:57 UTC, iwfua commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>  }
добавил

2024-10-26 09:57 UTC, iwfua commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
>      public ItemDto addItem(@Valid @RequestBody ItemDto itemDTO,
подправил

2024-10-26 21:23 UTC, YazykovMikhail approved these changes

2024-10-29 21:31 UTC, merged