Add item requests and gateway
iwfua/java-shareit pull request #6
Opened 2024-12-05 12:32 UTC by iwfua

2024-12-07 11:50 UTC, VadimZharkov commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +@Service
Лучше использовать `@Component`, `@Service` по соглашению используют на классах, отвечающих за бизнес-логику.

2024-12-07 11:53 UTC, VadimZharkov commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +			@Positive @RequestParam(name = "size", defaultValue = "10") Integer size) {
name = "size" не нужно указывать, если name совпадает с именем параметра метода

2024-12-07 11:58 UTC, VadimZharkov commented on gateway/src/main/java/ru/practicum/shareit/handle/ErrorHandle.java
> +}
Нужно добавить обработку MethodArgumentNotValidException в статус BAD_REQUEST (возникнет в контроллере на `@Valid`).
И добавить обработку всех оставшихся исключений: Throwable  в статус INTERNAL_SERVER_ERROR

2024-12-07 12:01 UTC, VadimZharkov commented on server/src/main/java/ru/practicum/shareit/handle/ErrorHandle.java
Добавить обработку Throwable

2024-12-07 12:03 UTC, VadimZharkov requested changes
Можно улучшить

2024-12-07 17:00 UTC, iwfua commented on gateway/src/main/java/ru/practicum/shareit/handle/ErrorHandle.java
> +}
Исправил

2024-12-07 17:00 UTC, iwfua commented on server/src/main/java/ru/practicum/shareit/handle/ErrorHandle.java
Ипсравил

2024-12-07 17:00 UTC, iwfua commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +			@Positive @RequestParam(name = "size", defaultValue = "10") Integer size) {
Исправил

2024-12-07 17:00 UTC, iwfua commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +@Service
Исправил

2024-12-08 06:30 UTC, VadimZharkov approved these changes

2024-12-08 20:53 UTC, merged